---
title: "Notas_bayesiana"
author: "Aishameriane Schmidt"
date: "28 de março de 2017"
output: pdf_document
---

# Aula 5 - Introdução à Inferência Bayesiana

Vamos utilizar a distribuição beta pois ela é conjugada da distribuição Bernoulli.

Cria os gráficos:
```{r}
require(ggplot2)
x <- seq(0, 1, len = 100)

p <- qplot(x, geom = "blank")
stat1 <- stat_function(aes(x = x, y = ..y..), 
                       fun = dbeta, colour="red", 
                       n = 100, 
                       args = list(shape1 = .5, shape2 = .5))
p1 <- p + stat1 + ggtitle("alpha = beta = .5")

p <- qplot(x, geom = "blank")
stat2 <- stat_function(aes(x = x, y = ..y..), 
                       fun = dbeta, colour="red", 
                       n = 100, 
                       args = list(shape1 = 1, shape2 = 1))
p2 <- p + stat2+ ggtitle("alpha = beta = 1")

p <- qplot(x, geom = "blank")
stat3 <- stat_function(aes(x = x, y = ..y..), 
                       fun = dbeta, colour="red", 
                       n = 100, 
                       args = list(shape1 = 10, shape2 = 10))
p3 <- p + stat3+ ggtitle("alpha = beta = 10")

p <- qplot(x, geom = "blank")

stat4 <- stat_function(aes(x = x, y = ..y..), 
                       fun = dbeta, colour="red", 
                       n = 100, 
                       args = list(shape1 = 5, shape2 = 2))
p4 <- p + stat4+ ggtitle("alpha = 5,beta = 2")
```
Função para múltiplos gráficos juntos (tirei [daqui](http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_(ggplot2)/)):
```{r}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

multiplot(p1, p2, p3, p4, cols=2)
```

Salva a figura em PDF:

```{r, eval = FALSE}
pdf(file="C:\\Users\\Aishameriane\\OneDrive\\Documentos\\Mestrado Economia\\Bayesiana - 2017-01\\Imagens notas de aula\\beta.pdf")
multiplot(p1, p2, p3, p4, cols=2)
dev.off()
```
